name: Upload
description: Upload artifacts
author: Wilfried Kopp <chevdor@gmail.com>
branding:
  icon: "package"
  color: "green"

inputs:
  AWS_ACCESS_KEY_ID:
    description: The AWS Key to be used. Make sure it has the required access rights
    required: true

  AWS_SECRET_ACCESS_KEY:
    description: The AWS secret key
    required: true

  AWS_BUCKET:
    description: AWS Bucket
    required: true

  AWS_REGION:
    description: The AWS region
    required: true

  public:
    description: >
      NOT IMPLEMENTED YET
      Whether the artifacts should be uploaded as public or not. Please note that some backends do not allow private uploads.
    default: "false"
    required: true

  product:
    description: Project
    required: true

  arch:
    description: arch
    required: false

  version:
    description: version
    required: true

  file_name:
    description: input file
    required: true

  target_path:
    description: Target path
    required: true

  labels:
    description: >
      NOT IMPLEMENTED YET
      An array of labels
    required: false

  overwrite:
    description: >
      Allows overwriting if the file already exists
    required: false
    default: "false"

  # Checksums
  md5:
    description: >
      NOT IMPLEMENTED YET
      Should generate a md5 checksum ?
    default: "false"

  sha256:
    description: >
      NOT IMPLEMENTED YET
      Should generate a sha256 checksum ?
    default: "false"

  image:
    description: >
      Docker image to be used. This is usually not something you want to change
      unless you know what you are doing
    required: true
    default: "paritytech/releng-scripts"

outputs:
  url:
    description: >
      URL of the uploaded artifact
    value: ${{ steps.upload.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Fetch Docker image
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: docker pull -q $IMAGE

    - name: Upload ${{ inputs.file_name }}
      id: upload
      env:
        IMAGE: ${{ inputs.image }}
        FILE: ${{ inputs.file_name }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ inputs.AWS_REGION }}
        AWS_BUCKET: ${{ inputs.AWS_BUCKET }}
        PRODUCT: ${{ inputs.product }}
        ARCH: ${{ inputs.arch }}
        VERSION: ${{ inputs.version }}
        OVERWRITE: ${{inputs.overwrite}}
      shell: bash
      run: |
        shopt -s expand_aliases
        VOL=/data

        alias rs="docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_REGION -e AWS_BUCKET -v $PWD:$VOL $IMAGE"
        alias awscli="docker run --rm  -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_REGION -e AWS_BUCKET -e AWS_CONFIG_FILE paritytech/awscli"

        echo "Running rs image version: $(rs version)"
        echo "Running awscli image version: $(awscli version)"
        echo "Overwrite: ${OVERWRITE}"

        [[ "$OVERWRITE" == "true" ]] && OVERWRITE_ARGS=" --overwrite " || OVERWRITE_ARGS=""
        [[ ! -z "$ARCH" ]]; && upload_path="${PRODUCT}/${VERSION}/${ARCH}" || upload_path="${PRODUCT}/${VERSION}"

        echo "upload_path: $upload_path"

        ls -al
        echo "Upload of $FILE"
        rs upload ${OVERWRITE_ARGS} \
          --bucket "${AWS_BUCKET}" \
          custom \
          ${upload_path} \
          s3 \
          "$VOL/${FILE}"

        # TODO: we don't want to see ALL
        echo "Check: https://${AWS_BUCKET}.s3.${AWS_DEFAULT_REGION}.amazonaws.com/index.html"
        awscli aws s3 ls ${AWS_BUCKET} --summarize
        awscli aws s3 ls ${AWS_BUCKET} --human-readable --recursive
