name: Check GHA Upload

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    # env: 

    steps:
      - name: Install Tools
        run: |
          wget -O ${{ runner.temp }}/just.tar.gz https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz && \
          tar xf ${{ runner.temp }}/just.tar.gz && mv just /usr/local/bin && \
          wget -O ${{ runner.temp }}/tera.deb https://github.com/chevdor/tera-cli/releases/download/v${TERA_VERSION}/tera-cli_linux_amd64.deb && \
          sudo dpkg -i ${{ runner.temp }}/tera.deb && \
          wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Render Doc
        run: |
          just md
