name: Check GHA Upload

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ["foo.txt", "bar.txt"]
    # env:

    steps:
      - name: Fetch GHA
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          path: action

      - name: Prepare test file ${{ matrix.file }}
        run: |
          echo "foobar" > ${{ matrix.file }}
          ls -al --color

      - name: Upload file ${{ matrix.file }}
        uses: ./action/release/artifacts/upload
        with:
          product: gha-artifacts-upload-tests
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_BUCKET: test-parity-release-engineering
          version: 1.2.3
          file: "${{ matrix.file }}"
