name: Send a text every minute
on:
  release:
    types:
      - prereleased
      - published
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.1
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: "GitHub Actions test for notifications, please Ignore"
         formatted_message: "<strong>${{github.event.repository.full_name}}:  ${{github.event.repository.html_url}}  <br/>GitHub Actions BOT Test</strong><br/>"
         server: "matrix.parity.io"
