name: Send a text every minute
on:
  release:
    types:
      - created
      - edited
      - prereleased
      - published
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.1
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: "GitHub Actions test for notifications, please Ignore"
         formatted_message: "<strong>${{github.release.html_url}}:  ${{github.event.release.tag_name}} <br/>Without event: ${{github.release.body}} <br/>With event: ${{github.event.release.body}} GitHub Actions BOT Test</strong><br/>"
         server: "matrix.parity.io"
