name: Send a text every minute
on:
  release:
    types:
      - created
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.1
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: "GitHub Actions test for notifications, please Ignore"
         formatted_message: "<strong>GitHub Actions BOT Test</strong>"
         server: "matrix.parity.io"
