name: Send a text every minute
on:
  release:
    types:
      - edited
      - prereleased
      - published
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.1
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: "GitHub Actions test for notifications, please Ignore"
         formatted_message: ""
         server: "matrix.parity.io"<strong>${{github.event.repository.full_name}}:</strong> A release has been ${{github.event.action}}<br/>Release version <a href=\"${{github.event.release.html_url}}\">${{github.event.release.tag_name}}</a><br/><br/>Description:<br/>${{github.event.release.body}}<br/>Body HTML??: ${{github.event.release.body_html}}
