name: Send a text every minute
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.1
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: "GitHub Actions test for notifications, please Ignore"
         formatted_message: "<strong>Please</strong><br /><em>ignore!</em>"
         server: "matrix.parity.io"
