name: Manual Upload

on:
  workflow_dispatch:
    inputs:
      region:
        type: choice
        description: The region to be used
        options:
          - eu-central-1
          - us-east-1
        default: eu-central-1

      overwrite:
        type: boolean
        description: Overwrite if artifacts are already present ?
        required: true
        default: false

      bucket:
        description: Bucket to be used
        required: true
        default: test-parity-release-engineering

      file_name:
        description: The file will be generated but you can set its name
        required: true
        default: foo.txt

defaults:
  run:
    shell: bash

jobs:
  manual_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch GHA
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          path: action

      - name: Prepare test file ${{ github.event.inputs.file_name }}
        run: |
          echo "foobar" > ${{ github.event.inputs.file_name }}
          ls -al --color

      - name: Upload file ${{ github.event.inputs.file_name }}
        uses: ./action/release/artifacts/upload
        with:
          product: gha-artifacts-upload-tests
          version: 1.2.3
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ github.event.inputs.region }}
          AWS_BUCKET: ${{ github.event.inputs.bucket }}
          file_name: ${{ github.event.inputs.file_name }}
          overwrite: ${{ github.event.inputs.overwrite }}
